### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GhostMaree** [MysteryDash/Offline-PS4-Remote-Play#1]
![image](https://user-images.githubusercontent.com/9166822/30519926-f25033f8-9ba2-11e7-8d4f-2bc1a227131b.png)

**Comment by MysteryDash** [comment]
Hello,
I need more details about your environment (OS, etc..).

**Comment by SaucyOfficiale** [comment]
Mine had that issue as well, I repatched it and it's giving me the same issue as before, without that warning. It starts to check an update with no wifi, then 2 seconds later says "PS4 Remote Play has stopped working". My application size is 4,748 KB, slightly less than the original. It wont open.

**Comment by MysteryDash** [comment]
Perhaps has the version changed, can you give me the version of the Remote Play you're using ?

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by MysteryDash** [comment]
If you could zip the whole remote play and send it to me I could get a better appreciation of the problem.
Thank you.

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by SaucyOfficiale** [comment]
Here is the official version of remote play I have installed for PC, from https://remoteplay.dl.playstation.net/remoteplay/lang/en/index.html

[Remote Play.zip](https://github.com/MysteryDash/Offline-PS4-Remote-Play/files/1319071/Remote.Play.zip)

**Comment by MysteryDash** [comment]
Okay so, for the first issue @GhostMaree reported I'm pretty sure it's OS-related, I'd need more details about his envrionment to fix it.  
As for you @SaucyOfficiale, I've been able to reproduce the issue (the patch removes too much information for some reason), so I'm going to fix it.

**Comment by GhostMaree** [comment]
windows 7 xd

**Comment by MysteryDash** [comment]
I updated the patch, so now it doesn't crash anymore @SaucyOfficiale .
As for the patcher itself @GhostMaree that's because you're using Windows 7 32-bits. I'm updating the patcher so that it uses a 32-bits version of xdelta.

**Comment by MysteryDash** [comment]
I've updated the release too (if you aren't directly downloading it from master).

**Comment by SaucyOfficiale** [comment]
It works, AMAZING! Thanks so much. :3

**Comment by MysteryDash** [comment]
My pleasure :).

-------- Message d'origine --------

**Comment by SaucyOfficiale** [comment]
Nvm its not working... It allows me into Remote Play (doesn't crash). However, it still tells me I need internet connection, when I hit the "option" button on my controller.
![screenshot 551](https://user-images.githubusercontent.com/23647313/30725856-856f43fc-9f15-11e7-9122-6232ff244f1f.png)

**Comment by MysteryDash** [comment]
Now that's a weird one.
Well I know what's left for me to do.

**Comment by MysteryDash** [comment]
By the way, like this you won't get anywhere.
You need a Wi-Fi connection or a wired link to your PS4 to make the Remote Play works (it's not black magic) !
Personally I connected my ps4 to my pc with an ethernet cable and made a bridge to my wireless card so that it always work instantly.
Without even a local network you just can't find your PS4.

**Comment by MysteryDash** [comment]
So currently @SaucyOfficiale it seems to me like this error is normal.

**Comment by SaucyOfficiale** [comment]
Okay, thank you.
