### ISSUE TITLE
error donwload patches

### ISSUE THREAD

**Issue by John677** [MysteryDash/Offline-PS4-Remote-Play#11]
windows 10 
I can't patch the file.
![ps4 remote play patcher_2018-05-08_11-51-34](https://user-images.githubusercontent.com/19402400/39747508-2c786ef4-52b6-11e8-9b33-e796abe743df.png)

**Comment by MysteryDash** [comment]
Hello,  
What version (of the Remote Play) do you currently have on your computer ?  
Are you sure that the Remote Play hasn't already been patched ?

**Comment by John677** [comment]
I didn't patch file before 
ver 2.5.0.9220
![explorer_2018-05-08_13-26-11](https://user-images.githubusercontent.com/19402400/39752197-6366d6be-52c3-11e8-898d-0d07dd6d325e.png)

**Comment by MysteryDash** [comment]
I don't have this version of the Remote Play, that's why I never made a patch for it before.  
Would it be possible for you to send me the installer ?

**Comment by John677** [comment]
unfortunately I have updated this version right from the app and I have no update file left. If you need i can pack to archive this version 
[PS4 Remote Play.zip (Linked removed)](/)

**Comment by MysteryDash** [comment]
It's okay, I'll make a patch for it.

**Comment by John677** [comment]
Hey how's it going? Or do I need to upgrade to a working version?

**Comment by MysteryDash** [comment]
I'm sorry I currently don't have time for this, I'll do it in a few weeks. A lower or higher version should work, yes.
