### ISSUE TITLE
Error 0x80001fff when start the remote play, option button on controller

### ISSUE THREAD

**Issue by SunLaria** [MysteryDash/Offline-PS4-Remote-Play#17]
When i starting the remote play with the controller or clicking start on the remote play program its saying 
error 0x80001fff any suggestion for solution

**Comment by MysteryDash** [comment]
There could be a lot of things going on behind this error code, did you try this : https://community.playstation.com/content/pdc/us/en_US/pdc-communities/support/Consoles-Peripherals.topic.html/remote_play_error0x-KJOW.html ?
