### ISSUE TITLE
Not working. Remote play is saying it needs latest firmware on ps4.

### ISSUE THREAD

**Issue by TheCoder2132** [MysteryDash/Offline-PS4-Remote-Play#18]
I have not connected to psn even once with my remote play app. Maybe this is causing it?If yes is there any way to bypass this?I have older ps4 remote play version 2.6.0.2270

**Comment by MysteryDash** [comment]
On the PS4 as long as you connected to the PSN before it's fine.  
On the PC you have to connect at least once to the PSN, so before going offline you have to be online at least once (that can be done without upgrading your PS4, of course, because it only happens on the computer).

**Comment by TheCoder2132** [comment]
@MysteryDash  I reinstalled remote play v1.0.0.15181 and signed in. Then I removed network connection and clicked on start. It says searching for ps4 and then a dialog box comes and says .
"Ps4 Remote Play will close because it must be update. The next time you open the application, the update will start."
I have used your patcher. Is there any way I could make my remote play work?

**Comment by MysteryDash** [comment]
The Remote Play version you used may not be compatible with your PS4 version of you see this message.
Every Remote Play isn't compatible with every PS4 version.

**Comment by TheCoder2132** [comment]
@MysteryDash Thank you so much. Finally got it working.
