### ISSUE TITLE
Patch doesn't work

### ISSUE THREAD

**Issue by mentionmenot** [MysteryDash/Offline-PS4-Remote-Play#2]
It seems this path doesn't work for Remote Play newest version. I tried and it required the internet connection to check update. Could you please share Remote Play ver. 2.0.0.2211 or make an update your patch?

**Comment by NoWhereMan1979** [comment]
I used the patch it doent appear to have any difference with original app.
connects through the internet

**Comment by MysteryDash** [comment]
The patch may be outdated, give me some time to check that.

**Comment by NoWhereMan1979** [comment]
Thank you for attention
For info i have a ps4 pro it may have different remote play version inside

**Comment by mentionmenot** [comment]
Thank you in advance!

**Comment by MysteryDash** [comment]
As predicted, there is a new version of the Remote Play (2.5.0.9220). Of course, the patch is version-specific, so I have to make another one, it'll be done in a few hours if everything is going as planned.

**Comment by MysteryDash** [comment]
Alright, the new patch is done (ece0b5e).
I am waiting a confirmation from you that it works and I'll close this issue.

**Comment by NoWhereMan1979** [comment]
I was so excited to test the patch but my one month age remote play app
doesn't work before update. The internet here went almost offline again.
I'll test the patcher as soon as possible

**Comment by mentionmenot** [comment]
Thank you MysteryDash. It works fine for me now.
