### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by agravkire** [MysteryDash/Offline-PS4-Remote-Play#20]
Would it be possible ? Fiddler with android app isnt working for me.

**Comment by darkroar360** [comment]
Not on any current version of the app, and it would probably require a fw below 3.00.

**Comment by MysteryDash** [comment]
I'm leaving this issue open in case anyone want to try messing around with the Android app.  
But if it hasn't been updated in a long time, then yeah it's basically going to be useless.

**Comment by coldestheart** [comment]
Man, Android Remote Play app by sony no need to be patched, just connect ps4 to the same wifi as your phone and sign-in in remote play app. After autosearching ps4 you could enter pincode from ps4, but before entering pin disable internet on your access point. Good luck! Tested on my 5.05
