### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JChangarirang** [MysteryDash/Offline-PS4-Remote-Play#21]
Hi, I get the following error when patcher is launched.

An error occured while downloading the latest patches.
System.Exception: Patch not found or RemotePlay.exe is already patched!
at
Dash.RemotePlayPatcher.Main. <> c__DisplayClass6_0.<Main_Load>b__2()

**Comment by MysteryDash** [comment]
Hello,
What's the version of your RemotePlay?

**Comment by nazsol** [comment]
Same problem here, it seems as though there is a new version of Remote Play - 2.7.0.7270.

**Comment by MysteryDash** [comment]
Okay, I'll check this out as soon as possible.

**Comment by JChangarirang** [comment]
I am having problem with the 2.6.0.2270.

**Comment by MysteryDash** [comment]
The 2.6.0.2270 should be supported, did you try reinstalling it?

**Comment by wcyee26** [comment]
I'm trying to change the codes of v**2.7.0.32668** in function `webClient_0_DownloadFileCompleted`: 

`private void webClient_0_DownloadFileCompleted(object sender, AsyncCompletedEventArgs e)`
`{`
`	if (e.Cancelled)`
`	{`
`		this.bool_5 = (Class8.smethod_0(2) != 0);`
`	}`
`	else if (e.Error != null)`
`	{`
`		this.bool_1 = (Class8.smethod_0(2) != 0); // removed this`
`		this.bool_5 = (Class8.smethod_0(2) != 0); // removed this`
`	}`
`       else{ `
`               // Bunch of deserialization codes (ignore this section)`
`       }`
`       this.bool_2 = (Class8.smethod_0(2) != 0); // set this to true`
`}`

I manage to skip the first step where it shows **Checking update...**.

But it doesn't work on the 2nd step where i have to press **Start**. After i pressed **Start**, it will prompt that it can't connect to the internet.

**Comment by MysteryDash** [comment]
Did you check the click event of the Start button?

**Comment by Md-Jomir-Hossain** [comment]
bro i got this same problem in my pc

An error occured while downloading the latest patches.
System.Exception: Patch not found or RemotePlay.exe is already patched!
at
Dash.RemotePlayPatcher.Main. <> c__DisplayClass6_0.<Main_Load>b__2()

plz help us to get out of this problem

**Comment by MysteryDash** [comment]
Version used?

**Comment by Md-Jomir-Hossain** [comment]
Broi am using the ps4 remote play   lstest version 2.7. It is update automatically
