### ISSUE TITLE
Stopped Working Circa Dec. 22, 2018

### ISSUE THREAD

**Issue by arkon317** [MysteryDash/Offline-PS4-Remote-Play#23]
I'm a huge fan of this app and use it nearly every single day - thank you so much for it! Encountered a 
 problem and I'm curious if this is only my own experience. 

I've been using Offline-PS4-Remote-Play since April 2018 (auto patched version of 2.0.0.02211). It suddenly started showing a new behavior around December 22, 2018 and as far as I can tell I haven't made any computer or PS4 configuration changes (PS4 is running the latest system software). New behavior after clicking Start:

"Searching for PS4"
"Connecting to the PS4"
Alert: "Cannot connect to the PS4. (0x80001fff)"

Anti-virus is not blocking the app, but it does show logs for IP addresses the app is attempting to connect to. This surprised me as I assumed the patcher must nuke those. I'm wondering if perhaps Sony has changed their Remote Play endpoints thus resulting in an error.

**Comment by MysteryDash** [comment]
Hmm, are you sure that the PS4 Remote Play has not been somehow updated?
You can easily check that in the software itself.

**Comment by arkon317** [comment]
Thanks for replying, MysteryDash! Yes, I can confirm that error occurs with an auto patched version of 2.0.0.02211 PS4 Remote Play. 

Can you confirm that you don't experience this issue with an older version? If you're not experiencing this issue with these old versions, then it must clearly be an issue on my side! (I saw you updated the patch for use with Remote Play 2.7 - excellent. I can get 2.7 to work over the internet, but have not yet tried using the 2.7 patched version for local play.)

Thanks again for your hard work!

**Comment by MysteryDash** [comment]
I also just published an auto patcher which should be compatible with every past and future versions of the RemotePlay, you might want to check it out.  
I played a lot with the RemotePlay and got this error (0x80001FFF) quite often, usually to solve it I had to either:  
- Restart my PS4 and the RemotePlay
- Make the ethernet bridge correctly (sometimes the PS4 was connected but couldn't get an IP address)
