### ISSUE TITLE
Source patching

### ISSUE THREAD

**Issue by mirh** [MysteryDash/Offline-PS4-Remote-Play#24]
I, for one, applaud the neat inclusion of the manual instructions. 
For the information behind the patching method never to die. 

But it seems a bit barbaric to include the raw bspatch, when (putting aside you could programmatically glue together the tools you mention) you could target the actual functions.. even possibly getting better at forward and backward compatibility. 
I mean: https://github.com/ioncodes/dnpatch

**Comment by MysteryDash** [comment]
Nah, it isn't going to happen, Sony pushes changes to the code of the Remote Play when they update it, so it's not always "look for function, remove this, enjoy".
There are more checks for updates in the most recent versions of the Remote Play than there were in the previous ones.

**Comment by mirh** [comment]
I mean, if they add new functions of course it's not like a program can reinvent the wheel for you. 
But assuming "stuff gets added incrementally" I would see lower maintenance burden (*looks at 2.7*)

Then, I guess like it would all depends on how much versatile/flexible the patching tool is.. But it doesn't seem like \*all that much\* required.

**Comment by MysteryDash** [comment]
I just added a new patch for 2.7 👍 .

**Comment by mirh** [comment]
Uh... 
*Cool*. 
Well, guess your call for everything eventually.

**Comment by MysteryDash** [comment]
You asked for it, so I've made it. Not with dnpatch though.

**Comment by mirh** [comment]
I mean, that was a suggestion. 
My point was just I loathe seeing "binaries" where "plain information" could be there (especially in source control). 
But last version works, so.. who cares for the time being? 😄

**Comment by MysteryDash** [comment]
Oh, I agree with you on that point, but I had to include the binaries for bspatch here because I know that they can easily disappear.
