### ISSUE TITLE
Using this patch without Sign in to PSN

### ISSUE THREAD

**Issue by MohandL3G** [MysteryDash/Offline-PS4-Remote-Play#28]
Hi, so I want to go completely offline when using PS4 Remote Play (because on my country we have blackout for about 4 to 6 hours, and I don't have internet at that time).
This is what i've done so far:
- Open PS4, run HEN then PS4REN, and then connect to my other router (which doesn't have internet connection), then go to Remote Play and Add Device and leave it there.
- Installed latest version of PS4 Remote Play and installed the latest Patch (this made PS4 Remote Play doesn't check for updates, Great) and make sure that I'm connected to the same router, then click Start.
- Then it shows a sign in window with blank white background.

To bypass this, I need to go online on my PC, Sign In, Then change network connection.
But, when I close it then run it again, it doesn't connect, and I have to select Change PS4 to connect to, and then go online again, Sign In, and change network connection.

Can you please fix this, and thank you so much.

**Comment by MysteryDash** [comment]
Hello,

If you are connected to the same PSN account as your PS4, it shouldn't ask you to login again when you start the software. I wouldn't recommend using the most recent version of the remote play with older versions of the PS4 too.

Also, did you try without the HEN?

-------- Message d'origine --------

**Comment by MohandL3G** [comment]
Hi,

Will I don't have a PSN account connected to my PS4, can I connect it with my jailbroken 5.05 PS4? as I thought we can't do that unless I update my PS4.
I'll try to test it with older versions.

and thanks for the reply.

**Comment by MysteryDash** [comment]
Not sure, I only have an up-to-date PS4.

What I'm sure of is that the PS4 has to be connected to a PSN account, I never had a case where it worked without that.

**Comment by MohandL3G** [comment]
So I tested I tried to run PS4REN which enable Remote Play, without loading HEN and it works.
but that's not my problem, my problem is with signing on PS4 Remote Play.

So I wanted to test this version "2.7.0.7270 - Hash : 9961E4475745881FAC537D58B1BCD5FB (seems to work without even logging to the Playstation Network)", but when I saw my installed version I found that it's 2.7.0.7270
![ps4rpv](https://user-images.githubusercontent.com/31743237/53918786-97df0100-4070-11e9-8fdb-711e03fc5a43.jpg)

So thanks for the reply, I think I'll ask on r/ps4homebrew someone might have a solution, thanks I really appreciate your help 😁

**Comment by MysteryDash** [comment]
Well, you can ignore the "Hash : XXX" part, this is meant for people who want to check whether or not their version has already been patched.

Let me know if /r/ps4homebrew is able to help you find a solution, it could help others here as well.
