### ISSUE TITLE
patched remote play not connecting to PS4

### ISSUE THREAD

**Issue by lilbud** [MysteryDash/Offline-PS4-Remote-Play#29]
Hello

I successfully patched remote play with the auto patcher. I have my PS4 connected via Ethernet to my computer, but remote play doesn't see my PS4.

Do I have to do anything further to use patched remote play? 

I am on newest version of PS4 (as of today, v7.5). I tried the most recent 3.0 version of Remote play, as well as an older version, 2.70. Neither work.

**Comment by lilbud** [comment]
Oh, forgot to attach this. The error I get upon trying to connect
![image](https://user-images.githubusercontent.com/9311410/79623957-c9881f80-80ec-11ea-816b-89c5946dfc72.png)

**Comment by MysteryDash** [comment]
Is your Remote Play client registered on your PS4?

**Comment by lilbud** [comment]
Yes, the remote play client is registered on my PS4 and works fully online.

**Comment by MysteryDash** [comment]
People online seem to say that when they have this error unregistering and manually pairing it again works, but I'm not really sure tbh.
