### ISSUE TITLE
"You must update the system software of the PS4"

### ISSUE THREAD

**Issue by Jimmy-Z** [MysteryDash/Offline-PS4-Remote-Play#3]
"The software will still ask you if you want to update it, however, you can now decline and still use the Remote Play !"

![image](https://user-images.githubusercontent.com/85773/32983150-5df854ec-cccb-11e7-8bdb-dcee4606debc.png)

How do I "decline"? If I press OK or close, it kicks me back to "Press the OPTIONS button on the controller to start" screen.

My PS4 is 4.55, I'm not actually trying to use it offline but just not want to upgrade my PS4 since recent homebrew development.

**Comment by MysteryDash** [comment]
That's not how it works, you can prevent the Remote Play's update, not the PS4's !

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by MysteryDash** [comment]
However, since you intend to use it where an Internet connection is not available, what you can try is put your PS4 offline, restart it and connect it to your local network without Internet, then it may not ask you for the update.
If it does, try using an older version of the Remote Play.

**Comment by Jimmy-Z** [comment]
Thanks for clarification.
