### ISSUE TITLE
It show me the log in screen but cant log in and cant use it

### ISSUE THREAD

**Issue by J0NY13** [MysteryDash/Offline-PS4-Remote-Play#31]
Hi :)
I wanted to ask if you know what is this number problem i get on remoteplay, i cant log in and previusly didnt had this problem o.O i tried looking for someone else happen this and dont for what i find o. o
everytime i try to conect to my ps4 it jump that log in screen and i cant log in ._ . that is why i try to log in, there is other way to not need of log in?
![coco](https://user-images.githubusercontent.com/64482505/80501240-97c15500-8945-11ea-87ac-1f4f4c1ebf86.png)

**Comment by MysteryDash** [comment]
I hadn't noticed you had already created your own issue, so I will quote myself:
> Your issue does not seem to be linked with the Remote Play itself, so try to login in your browser directly and see if it works.

AFAIK logging in at least once is required to connect to the PS4.

**Comment by J0NY13** [comment]
> 
> 
> I hadn't noticed you had already created your own issue, so I will quote myself:
> 
> > Your issue does not seem to be linked with the Remote Play itself, so try to login in your browser directly and see if it works.
> 
> AFAIK logging in at least once is required to connect to the PS4.

I found the problem i think so, it is region problem, that window open a link to Mexico PSN, while my account is from other country, but there is no way to change the country of the log in screen so it is stupid really and i cant log in to use the program T. T i re-instaled and nothing again, it is a permanent problem now and i cant use it anymore so im screwed....

**Comment by J0NY13** [comment]
oh and plus, my main acount i used to use the program get blocked.

**Comment by J0NY13** [comment]
Ok, found the reason, for some reason my own PC region was changed solo to Mexico region, if someone have the same problem say the same

Region changed if that mesenge apear on screen, took me 1 day to know, but yet idk how it changed if no one touch this PC ._ .
