### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by Scholl18** [MysteryDash/Offline-PS4-Remote-Play#32]
this version continues to ask me to sign in however since my laptop isnt connected to wifi i am unable to do this. any way around it?

**Comment by MysteryDash** [comment]
Hello,
Signing in is a necessary step that must be done at least once unfortunately, otherwise the RemotePlay will never accept to connect to the PS4. Once that's done though you can go fully offline and use the RemotePlay.

**Comment by Scholl18** [comment]
ahhh i see, i have to connect online once and then im all good
