### ISSUE TITLE
Update PS4 Software

### ISSUE THREAD

**Issue by Aurangzeb56** [MysteryDash/Offline-PS4-Remote-Play#33]
hey i just wanted to report a big that i encountered. I used the latest patch on the latest version of he remote play 3.0. The worked and everything, after I connected the PS4 through remote play , I got an error message to update the PS4 software. Could you please look into it? Thanks :)

**Comment by MysteryDash** [comment]
Hello,
What version is your PS4 using? If your PS4's OS is too old you can't use a recent version of the Remote Play.
I haven't looked so much into 3.0, and considering that they decided to call it a major update, I wouldn't be surprised if they broke the patcher.

**Comment by Aurangzeb56** [comment]
> Hello,
> What version is your PS4 using? If your PS4's OS is too old you can't use a recent version of the Remote Play.
> I haven't looked so much into 3.0, and considering that they decided to call it a major update, I wouldn't be surprised if they broke the patcher.

Hey there. I'm using 5.05 FW on my Ps4.

**EDIT:** So does that mean I'll have to stick with the older versions of remoteplay? I can't seem to find version 2.7

**Comment by MysteryDash** [comment]
You absolutely need to use an older version of the RemotePlay. You should be able to find them using the Wayback Machine.

**Comment by Aurangzeb56** [comment]
> You absolutely need to use an older version of the RemotePlay. You should be able to find them using the Wayback Machine.

Oh okay. Thanks. :D

 **EDIT** Sadly I just googled it and seems like I can not find that version.

**EDIT 2** Found it. Going to try it in the morning. Thanks. :)
