### ISSUE TITLE
Problem connecting trying to connect to psn

### ISSUE THREAD

**Issue by gregofigueras** [MysteryDash/Offline-PS4-Remote-Play#34]
Hi im having this problem. Do you know how to solve it?
![Issue](https://user-images.githubusercontent.com/65877630/82769619-c2e77900-9e0b-11ea-8e90-65783d1c61d2.jpg)

**Comment by MysteryDash** [comment]
Hello,
Could you give me more details about the version of the Remote Play you are using? I would need more details than just "An error has occured" to figure out what's going on.

**Comment by gregofigueras** [comment]
im running this version: 
![issue](https://user-images.githubusercontent.com/65877630/82848129-9d6c7500-9ec8-11ea-877d-55c229b44977.png)

**Comment by MysteryDash** [comment]
Were you able to login to the PSN? On Windows 7, IE11 is required to make the RemotePlay work (tbh it's not really a good idea to run Windows 7 anywhere anyway...).

**Comment by gregofigueras** [comment]
yes, i have it. I login in my psn account and then appear the error window.

**Comment by MysteryDash** [comment]
What version is your PS4 running?

**Comment by gregofigueras** [comment]
My PS4 is running the version 7.50

**Comment by MysteryDash** [comment]
You will very likely need a more recent version of the RemotePlay.
