### ISSUE TITLE
Ethernet Connection

### ISSUE THREAD

**Issue by zhao-lun** [MysteryDash/Offline-PS4-Remote-Play#35]
Hi, 
thank you for this patch. I have tried using mobile hotspot and it works like a charm. Well, i was wondering if i can use just Ethernet connection?

OS: windows 10

**Comment by MysteryDash** [comment]
Hello,
Sure! In fact, that's what I'd recommend doing. Just plug in an ethernet cable from your computer to your PS4 and it should work straight out of the box (or maybe you will need to bridge the connection, but it's not always mandatory).

**Comment by zhao-lun** [comment]
@MysteryDash 
thank you. Yes, using the bridge connection.
