### ISSUE TITLE
Remote Play Offline stuck at Checking for Updates

### ISSUE THREAD

**Issue by swb1990** [MysteryDash/Offline-PS4-Remote-Play#4]
Hi,

I patched the Remote Play using your one-click patcher.
After connecting my PS4 directly to my PC via Ethernet, I launched Remote Play but it gets stuck at "Checking for Updates"
As such, I am unable to progress any further.
Is there a need to assign a static IP address to both the PC and PS4?
Or are there other issues?

For info, I am running Win 10 Home 64 bits and I have a PS4 Slim
Thank you

**Comment by MysteryDash** [comment]
Hello,

Did you create a bridge between your laptop's Ethernet card and your Wi-Fi card ? IIRC this is a requirement to establish a connection between your computer and your laptop, then you need to enable connection sharing (I know that doesn't make sense since you won't be using Internet, but that's how I did it), and connect your PS4 in its settings using Ethernet.

You can check if the remote play was patched correctly in its information window.

-------- Message d'origine --------

**Comment by swb1990** [comment]
On which interface do I enable connection sharing? Wifi or Ethernet?
The newly created bridged adapter does not have the option to do connection sharing.

Currently my PS4 is connected to my router via Ethernet already.

the patched remote play is stuck at "Checking for Updates" so I can't even get to the Information window. In any case, what is it supposed to say in its Information window?

**Comment by MysteryDash** [comment]
Sorry I took the problem the wrong way, there must be something wrong with the patch, it shouldn't be stuck like this whether you've got the connection setup correctly or not.
Could you upload your patched RemotePlay.exe ? I'll check it to see if it was patched correctly, if not, we'll figure out why.

**Comment by swb1990** [comment]
No worries!
I was able to access the Information window if I have my usual Internet connection on.
It does says RemotePlay Offline so I suppose the patch is successful to some extent.
That said, it seems to still require me to have an active Internet connection.

[RemotePlay_offline.zip](https://github.com/MysteryDash/Offline-PS4-Remote-Play/files/1713928/RemotePlay_offline.zip)

**Comment by MysteryDash** [comment]
Hmm, it's correctly patched, I even disabled every network card I have and it was still able to start.
Could you try to do the same ? It's _(not)_ a totally random guess but... we never know.

**Comment by swb1990** [comment]
So to reiterate,
I bridge my Ethernet and Wireless interface, I enable Connection Sharing on my Ethernet interface
That's it?
Do I actually have to have a connection on my Wireless interface?

**Comment by swb1990** [comment]
Tried the simplest method of disabling all my network cards but I'm still stuck...=(

![error](https://user-images.githubusercontent.com/22560264/36068517-6d6ecd14-0f12-11e8-9a9f-27fe888bc6df.png)

**Comment by swb1990** [comment]
Ok I might have found the crux of the issue...
I'll test it a few more times to verify my hypothesis and if it is true, will post the cause =)

**Comment by MysteryDash** [comment]
Yes, and no, you don't need to have an actual connection. 
Great, I hope that it's what you think.

**Comment by swb1990** [comment]
I've found the cause of the issue!
In case anyone face the same problem, **if you have an overprotective antivirus that blocks almost all unknown exe, simply add it to Exception List.** I totally overlooked this...
There is no need to have a bridge connection or connect to a non-functional hotspot via Wifi.

Simply connect both PS4 and PC together via a Ethernet cable and it'll work ^^
Thanks for the prompt assist Dash!

**Comment by MysteryDash** [comment]
Great.

One my side the antivirus only blocks the sound that's coming out of the offline remote play (don't ask why the sound, I've got no idea...).

-------- Message d'origine --------
