### ISSUE TITLE
Hello is there any way to patch an older version, so a 4.05 PS4 could connect offline?

### ISSUE THREAD

**Issue by pupphelper** [MysteryDash/Offline-PS4-Remote-Play#5]
I have an original version of PS4 Remote PLay from 08/2016 which shouldn't have a higher firmware requirement.  But your patcher and xdelta patch didn't work on it.   The newest version, patches great and connects offline but when it gets to my 4.05 firmware ps4, it says i need to update the PS4 which I don't want to do for homebrew.

Any suggestions?

**Comment by MysteryDash** [comment]
Yes, the newest remote play uses new features so I can't just patch it for any version.
Please send me your current remote play so that I can create a patch for you (the installer or the exe file).

**Comment by sushyoshi** [comment]
I also have the same problem as pupphelper but I have a PS4 version 4.73 . However I cannot find anywhere a version of the installer that works with older ps4s. Could you send me one already patched? or Let me now how to do it.

**Comment by MysteryDash** [comment]
The instructions necessary to create a patch yourself are in the readme file.

-------- Message d'origine --------
On 4 mars 2018 à 18:17, sushyoshi a écrit :

I also have the same problem as pupphelper but I have a PS4 version 4.73 . However I cannot find anywhere a version of the installer that works with older ps4s. Could you send me one already patched? or Let me now how to do it.

**Comment by sushyoshi** [comment]
I cant seem to find an old remote play pc installation anywhere. I have tried searching for it and no luck.
Do you have one so that I can patch it myself?

**Comment by MysteryDash** [comment]
Using the Warback Machine from archive.org I was able to find an older version (early 2016, 1.0.0.15181 and early 2017, 2.0.0.2211).  
You can get it here : https://web.archive.org/web/20160408211121/https://remoteplay.dl.playstation.net/remoteplay/module/win/RemotePlayInstaller.exe. If you are unable to create the patch ping me here and I'll make it for you.  
I already made a patch for the version 2.0.0.2211, so you can download it by exploring the older commits of this repository.

**Comment by sushyoshi** [comment]
Thank you so much. I atually found it another way just browsing google for 2 hours. I already applied our patch and its working perfectly. Thank you very much you are very helpful!
