### ISSUE TITLE
As of the release of 5.50 firmware this patch is not working

### ISSUE THREAD

**Issue by pupphelper** [MysteryDash/Offline-PS4-Remote-Play#7]
Could you make the revised patch also work with older versions for those who prefer to stay on lower firmware?

**Comment by MysteryDash** [comment]
If it doesn't work anymore, then they updated it again.
Okay so, here's what I'm going to do : 
- Create patches for all versions of the Remote Play I'm able to get
- Make a new automated patcher so that it patches the version you currently have on your computer.

**Comment by pupphelper** [comment]
Thanks so much, your work is greatly appreciated.  This really is a silly requirement sony has.

**Comment by MysteryDash** [comment]
Fixed by 73da3da23f61765cc4f11be772e345f160595595
