### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by MajidAmini** [MysteryDash/Offline-PS4-Remote-Play#8]
Hi, i cant install remote play on windows 7, wondering if you could add this feature or help me somehow. Thank you so much!

**Comment by MysteryDash** [comment]
Hello, do you have an error message ?
You should also at some point upgrade to Windows 10, or the Remote Play will be the least of your worries when other softwares become incompatible with 7.

**Comment by MajidAmini** [comment]
Thanks for your answer, yes i got the error. honestly this is the only program that does not support windows 7 and that's so annoying.
i cant upgrade to windows 10 because of drivers stuff.

![capture](https://user-images.githubusercontent.com/16164002/37419815-8caaf808-27ca-11e8-935f-813fa0949030.PNG)

**Comment by MysteryDash** [comment]
The error is self explanatory, you will not be able to install this particular version of the PS4 Remote Play. However, unless your PS4 has been updated to the latest version, you can look for older versions of the PS4 Remote Play on archive.org's Wayback Machine. They may work on Windows 7.

**Comment by MajidAmini** [comment]
Unfortunately my ps4 updated to latest version, but thank you so much for helping me. i think i ran out of options!

**Comment by SilicaAndPina** [comment]
https://youtu.be/b6REy2U3flA @MajidAmini unsure if this still works its been awhile but here's a way you can ""install"" it.
