### ISSUE TITLE
problem downloading patches on Win 7

### ISSUE THREAD

**Issue by Payam-Fz** [MysteryDash/Offline-PS4-Remote-Play#9]
Hi there,
First of all I should thank you for your effort and time making this useful patch
Now about my issue;
I know remote play app is not designed for Win 7 but Sony does not support my Sony Vaio laptop to be upgraded to Win 10, Therfore I will have problems finding driver and... Anyway, I need to use Remote play on win 7. After searching in google I found that by extracting "RemotePlayInstaller" I will be able to run the app. But unfortunately, In the latest version of remote play app(V2.6) this method is useless
So what I did was to find an old version of the app which is compatible with your patch (V2.0.0) and patch it so that it won't connect to internet to check for update.
Unfortunately, I face an error window when the Patcher app of yours tries to download the compatible patch.
I tried this method on my brother's PC which runs Windows 10 and it worked properly!!
Even turned off Firewall to make sure internet connection is not restricted.
Also took a screenshot from the error for you.
My windows version: Windows 7 Professional SP1 with the Latest updates
Hope to hear from you
I really appreciate your help and your time devoting to this!

![issue](https://user-images.githubusercontent.com/38796591/39384615-b571d826-4a82-11e8-970c-21bdbeb43d7b.jpg)

**Comment by MysteryDash** [comment]
Yeah it's a Windows 7-only issue. I'm fixing it right now.

**Comment by MysteryDash** [comment]
I don't have a Windows 7 VM or computer ready to use so could you test this for me ?

[Patcher.zip](https://github.com/MysteryDash/Offline-PS4-Remote-Play/files/1956634/Patcher.zip)

**Comment by Payam-Fz** [comment]
Never seen such a fast support....
I'm speechless
Thank you so much

**Comment by MysteryDash** [comment]
So may I presume that it worked ?

**Comment by Payam-Fz** [comment]
Yess
Thats it... The problem is totally solved!!!
